### ISSUE TITLE
Support youtu.be and https src in iframe

### ISSUE THREAD

**Issue by tavriaforever** [hgarcia/oEmbed-node#7]
When I am trying to get youtube iframe, like this:
```
oembed.get({ url: 'https://youtu.be/1GWoMnYldYc/' }, function(err, result) {
    if (err) throw err;

    console.log('result', result);
});
```

I get the error:
```
undefined:1
Not Found
^
SyntaxError: Unexpected token N
    at Object.parse (native)
    at /Users/tavria/Sites/bem-md-renderer/node_modules/oembed-node/lib/request-handler.js:15:28
    at /Users/tavria/Sites/bem-md-renderer/node_modules/oembed-node/node_modules/curling/lib/curl-transport.js:57:5
    at ChildProcess.exithandler (child_process.js:645:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

After a bit debug, I find a problem. In this case link `https://youtu.be/1GWoMnYldYc/` haven`t query 'v', so the module broken down.

A replace code in this line https://github.com/hgarcia/oEmbed-node/blob/master/lib/providers/youtube.js#L15 to `parsedUrl.pathname.split('/')[1];` and after that I had had the result. 

But after this, I noticed, that the src of iframe had a `http` protocol, so on my site this video won`t work, becase website working with `https`

**Comment by hgarcia** [comment]
I will take a look at this shortly, thanks
